export type AppIconName =
  | 'archive'
  | 'arrow-right'
  | 'close'
  | 'dashboard'
  | 'document'
  | 'download'
  | 'menu'
  | 'profile'
  | 'refresh'
  | 'signature'
  | 'storage'
  | 'timestamp'
  | 'upload'
  | 'wallet'
